# Generated by Django 5.1.2 on 2024-11-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='minor',
            field=models.IntegerField(unique=True),
        ),
    ]
