# Generated by Django 5.1.2 on 2024-12-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='period',
        ),
    ]
