# Generated by Django 5.1.2 on 2024-10-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='instructor_id',
            new_name='teacher_id',
        ),
    ]
