# Generated by Django 5.1.2 on 2024-10-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_instructor_id_teacher_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='roll',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
