# Generated by Django 5.1.2 on 2024-12-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='is_special_class',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_special_class',
            field=models.BooleanField(default=False),
        ),
    ]
