# Generated by Django 5.1.2 on 2024-10-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_enrollment_subject_alter_teacher_roll_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='roll',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('period1', models.CharField(blank=True, max_length=100, null=True)),
                ('period2', models.CharField(blank=True, max_length=100, null=True)),
                ('period3', models.CharField(blank=True, max_length=100, null=True)),
                ('period4', models.CharField(blank=True, max_length=100, null=True)),
                ('is_special_class', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('email', 'date')},
            },
        ),
    ]
