# Generated by Django 5.1.2 on 2024-12-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_timetable_is_special_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='classroom_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
