# Generated by Django 5.1.2 on 2024-10-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_equipment_alter_teacher_roll_timetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='major',
            new_name='macaddress',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_id',
        ),
        migrations.AddField(
            model_name='equipment',
            name='minor',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
