# Generated by Django 5.1.2 on 2024-12-09 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_studentclass_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='classroom_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.classroom'),
        ),
    ]
