# Generated by Django 5.1.2 on 2024-12-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_studentclass_classroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='classroom_name',
        ),
    ]
